import { block, P_PERIOD } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Confirmation Logic (12) ──────────────────────────────────────────

export const CONFIRMATION_BLOCKS: BlockDefinition[] = [
  block({
    id: "confirm.rsiSide",
    family: "confirmation",
    subcategory: "indicator",
    name: "RSI Side Confirmation",
    short: "RSI must be on the correct side of a level.",
    long: "Allows longs only when RSI > longAbove, shorts only when RSI < shortBelow. Keeps you on the right side of momentum.",
    userWhy: "Filters out entries that disagree with momentum — an easy win for new users.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["momentum", "rsi"],
    params: [
      P_PERIOD("period", "RSI period", 14, 2, 200),
      { key: "longAbove", label: "Longs only when RSI >", kind: "number", default: 50,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 100 }] },
      { key: "shortBelow", label: "Shorts only when RSI <", kind: "number", default: 50,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "confirm.macdSide",
    family: "confirmation",
    subcategory: "indicator",
    name: "MACD Side Confirmation",
    short: "MACD histogram sign must match direction.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["momentum", "macd"],
    params: [P_PERIOD("fastPeriod", "Fast EMA", 12, 2), P_PERIOD("slowPeriod", "Slow EMA", 26, 2), P_PERIOD("signalPeriod", "Signal", 9, 1)],
  }),
  block({
    id: "confirm.stochSlope",
    family: "confirmation",
    subcategory: "indicator",
    name: "Stochastic Slope",
    short: "%K must be rising / falling with direction.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["momentum", "stochastic"],
    params: [P_PERIOD("kPeriod", "%K period", 14, 1)],
  }),
  block({
    id: "confirm.priceAboveMa",
    family: "confirmation",
    subcategory: "price-relation",
    name: "Price vs Moving Average",
    short: "Price must be above / below a given MA.",
    long: "Requires price to be on the bullish / bearish side of a moving average. Works like a lightweight trend filter.",
    userWhy: "The cheapest trend filter you can add. Big impact for one block.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["trend", "ma"],
    params: [
      { key: "maType", label: "MA type", kind: "select", default: "ema",
        options: [{ value: "ema", label: "EMA" }, { value: "sma", label: "SMA" }, { value: "wma", label: "WMA" }] },
      P_PERIOD("period", "Period", 50, 2),
    ],
  }),
  block({
    id: "confirm.priceVsVwap",
    family: "confirmation",
    subcategory: "price-relation",
    name: "Price vs VWAP",
    short: "Price relative to session VWAP.",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: true, tags: ["vwap", "volume"],
    params: [],
  }),
  block({
    id: "confirm.emaAlignment",
    family: "confirmation",
    subcategory: "price-relation",
    name: "EMA Alignment (3)",
    short: "Three EMAs stacked correctly for direction.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["trend", "ema"],
    params: [
      P_PERIOD("fastPeriod", "Fast EMA", 20, 2),
      P_PERIOD("midPeriod", "Mid EMA", 50, 2),
      P_PERIOD("slowPeriod", "Slow EMA", 200, 2),
    ],
  }),
  block({
    id: "confirm.higherHigh",
    family: "confirmation",
    subcategory: "price-relation",
    name: "Higher High / Higher Low",
    short: "Require confirmed HH / HL for long (mirror for short).",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: false, tags: ["structure", "swings"],
    params: [P_PERIOD("lookback", "Swing lookback", 10, 3)],
  }),
  block({
    id: "confirm.atrAboveMa",
    family: "confirmation",
    subcategory: "indicator",
    name: "ATR Above Its MA",
    short: "ATR must exceed its own N-period MA.",
    plan: "pro", priority: "P3", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["volatility", "atr"],
    params: [P_PERIOD("atrPeriod", "ATR period", 14, 1), P_PERIOD("maPeriod", "ATR-MA period", 50, 2)],
  }),
  block({
    id: "confirm.tickVolume",
    family: "confirmation",
    subcategory: "volume",
    name: "Tick Volume Spike",
    short: "Bar tick volume > k × average.",
    plan: "pro", priority: "P3", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["volume"],
    params: [
      P_PERIOD("lookback", "Volume MA lookback", 20, 2),
      { key: "multiplier", label: "Spike multiplier", kind: "number", default: 1.5,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "confirm.obvSlope",
    family: "confirmation",
    subcategory: "volume",
    name: "OBV Slope",
    short: "OBV rising / falling with direction.",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: true, tags: ["volume"],
    params: [P_PERIOD("lookback", "Slope lookback", 5, 2)],
  }),
  block({
    id: "confirm.barColor",
    family: "confirmation",
    subcategory: "price-relation",
    name: "Candle Color Match",
    short: "Prior candle must be bullish / bearish.",
    plan: "free", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: false, tags: ["price-action"],
    params: [
      { key: "candleOffset", label: "Candle offset", kind: "integer", default: 1,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 10 }] },
    ],
  }),
  block({
    id: "confirm.minBarsSinceSignal",
    family: "confirmation",
    subcategory: "time",
    name: "Cooldown Since Last Trade",
    short: "Block entries for N bars after the last one.",
    long: "Prevents rapid re-entries by suppressing the entry rule for a cooldown window after the last fill.",
    userWhy: "Stops the EA from rapid-firing on noise. Cheap way to smooth a choppy strategy.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: false, tags: ["cooldown", "behaviour"],
    params: [
      { key: "minBars", label: "Minimum bars", kind: "integer", default: 5, unit: "bars",
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 500 }] },
    ],
  }),
];
