import { block, P_DIRECTION, P_PERIOD } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Entry Logic (22) ─────────────────────────────────────────────────
// Crossovers / breakouts / reversals / zone / pattern triggers / composite.
// V1 active: emaCross, smaCross, macdCross, stochCross, previousCandle,
// donchianBreakout, bollingerBreak, rsiExtreme.

export const ENTRY_BLOCKS: BlockDefinition[] = [
  // ── crossovers ──
  block({
    id: "entry.emaCross",
    family: "entry",
    subcategory: "crossover",
    name: "EMA Cross",
    short: "Buy/sell when fast EMA crosses slow EMA.",
    long: "Classic two-EMA crossover. Fires long on fast-crosses-above-slow, short on the opposite. Commonly used as the backbone of trend-following strategies.",
    userWhy: "The simplest trend-following trigger. Starts strategies on the right foot when paired with a trend filter.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["trend", "crossover", "ema", "classic"],
    params: [
      P_PERIOD("fastPeriod", "Fast EMA", 20, 2, 500),
      P_PERIOD("slowPeriod", "Slow EMA", 50, 2, 500),
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.smaCross",
    family: "entry",
    subcategory: "crossover",
    name: "SMA Cross",
    short: "Buy/sell when fast SMA crosses slow SMA.",
    long: "Same as EMA Cross but with simple moving averages. Included because many classic systems (golden / death cross) are specified in SMA.",
    userWhy: "Use when you want to match classic SMA systems exactly rather than faster EMAs.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["trend", "crossover", "sma"],
    params: [
      P_PERIOD("fastPeriod", "Fast SMA", 20, 2, 500),
      P_PERIOD("slowPeriod", "Slow SMA", 50, 2, 500),
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.macdCross",
    family: "entry",
    subcategory: "crossover",
    name: "MACD Cross",
    short: "Enter when MACD line crosses the signal line.",
    long: "Fires on MACD-line crossing the signal line. With `histogramOnly` enabled, requires a histogram sign flip instead of the line cross — a slightly earlier entry.",
    userWhy: "A staple momentum trigger. Tends to work best when combined with a trend filter.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["momentum", "crossover", "macd"],
    params: [
      P_PERIOD("fastPeriod", "Fast EMA", 12, 2),
      P_PERIOD("slowPeriod", "Slow EMA", 26, 2),
      P_PERIOD("signalPeriod", "Signal period", 9, 1),
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.macdZeroCross",
    family: "entry",
    subcategory: "crossover",
    name: "MACD Zero Line",
    short: "Enter when MACD crosses above / below zero.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["entry"], mt5: true, tags: ["momentum", "macd", "regime"],
    params: [P_PERIOD("fastPeriod", "Fast EMA", 12, 2), P_PERIOD("slowPeriod", "Slow EMA", 26, 2), P_DIRECTION],
  }),
  block({
    id: "entry.stochCross",
    family: "entry",
    subcategory: "crossover",
    name: "Stochastic Cross",
    short: "%K / %D cross inside overbought / oversold.",
    long: "Requires a %K / %D crossover while the indicator is in an extreme zone. A slower, cleaner version of the classic stochastic signal.",
    userWhy: "Filters out noisy stoch crosses in the middle of the range.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["reversal", "stochastic", "oscillator"],
    params: [
      P_PERIOD("kPeriod", "%K period", 14, 1),
      P_PERIOD("dPeriod", "%D period", 3, 1),
      P_PERIOD("slowing", "Slowing", 3, 1),
      { key: "overbought", label: "Overbought level", kind: "number", default: 80, unit: "%",
        validation: [{ kind: "min", value: 50 }, { kind: "max", value: 100 }] },
      { key: "oversold", label: "Oversold level", kind: "number", default: 20, unit: "%",
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 50 }] },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.rsiCross",
    family: "entry",
    subcategory: "crossover",
    name: "RSI Centerline",
    short: "RSI crosses 50.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["momentum", "rsi"],
    params: [P_PERIOD("period", "RSI period", 14, 2, 200), P_DIRECTION],
  }),
  block({
    id: "entry.adxCross",
    family: "entry",
    subcategory: "crossover",
    name: "ADX Regime Entry",
    short: "ADX crosses activation threshold.",
    plan: "pro", priority: "P3", complexity: "intermediate", status: "beta",
    affects: ["entry"], mt5: true, tags: ["trend", "adx"],
    params: [
      P_PERIOD("period", "ADX period", 14, 2),
      { key: "threshold", label: "Activation ADX", kind: "number", default: 20,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 100 }] },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.ichimokuKijun",
    family: "entry",
    subcategory: "crossover",
    name: "Ichimoku Kijun Cross",
    short: "Price crosses Kijun-sen with cloud-side filter.",
    plan: "pro", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["entry"], mt5: true, tags: ["ichimoku", "advanced"],
    params: [
      P_PERIOD("tenkan", "Tenkan period", 9, 1),
      P_PERIOD("kijun", "Kijun period", 26, 1),
      P_PERIOD("senkou", "Senkou period", 52, 1),
      P_DIRECTION,
    ],
  }),

  // ── breakouts ──
  block({
    id: "entry.donchianBreakout",
    family: "entry",
    subcategory: "breakout",
    name: "Donchian Breakout",
    short: "Close outside N-bar Donchian channel.",
    long: "Fires long on a close above the N-bar high, short on a close below the N-bar low. Turtle-style breakout baseline.",
    userWhy: "Clean, robust breakout trigger that works across trendy markets.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["entry"], mt5: true, tags: ["breakout", "donchian", "turtle"],
    params: [P_PERIOD("period", "Channel period", 20, 5), P_DIRECTION],
  }),
  block({
    id: "entry.bollingerBreak",
    family: "entry",
    subcategory: "breakout",
    name: "Bollinger Breakout",
    short: "Close outside Bollinger envelope.",
    long: "Close above the upper band fires long; close below the lower band fires short. Pairs best with a trend filter to avoid reversals.",
    userWhy: "Volatility-aware breakout. Reacts to market expansion rather than fixed pip distances.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["entry"], mt5: true, tags: ["breakout", "bollinger", "volatility"],
    params: [
      P_PERIOD("period", "Period", 20, 5),
      { key: "deviation", label: "Deviation (σ)", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 0.5 }, { kind: "max", value: 5 }, { kind: "step", value: 0.1 }] },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.previousCandle",
    family: "entry",
    subcategory: "breakout",
    name: "Previous Candle Break",
    short: "Break of previous candle high / low.",
    long: "Enter long when price breaks the previous candle's high, short on the low. Respects an optional minimum range so tiny candles don't fire.",
    userWhy: "Simplest possible breakout. Great starter block — pair with an HTF trend filter.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: false, tags: ["breakout", "price-action"],
    params: [
      P_DIRECTION,
      { key: "minRangePips", label: "Minimum candle range", kind: "number", default: 5, unit: "pips",
        validation: [{ kind: "min", value: 0 }] },
    ],
  }),
  block({
    id: "entry.nBarBreakout",
    family: "entry",
    subcategory: "breakout",
    name: "N-Bar High/Low Breakout",
    short: "Break of N-bar high / low (no channel drawn).",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["entry"], mt5: false, tags: ["breakout"],
    params: [P_PERIOD("period", "Bars", 10, 2), P_DIRECTION],
  }),
  block({
    id: "entry.atrBreakout",
    family: "entry",
    subcategory: "breakout",
    name: "ATR Volatility Breakout",
    short: "Bar open ± k × ATR hit.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["entry"], mt5: true, tags: ["breakout", "atr", "volatility"],
    params: [
      P_PERIOD("atrPeriod", "ATR period", 14, 1),
      { key: "multiplier", label: "ATR multiplier", kind: "number", default: 1.0,
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.sessionBreakout",
    family: "entry",
    subcategory: "breakout",
    name: "Session Range Breakout",
    short: "Break of prior session range.",
    plan: "creator", priority: "P2", complexity: "intermediate", status: "beta",
    affects: ["entry"], mt5: false, tags: ["breakout", "session"],
    params: [
      { key: "session", label: "Session", kind: "select", default: "asia",
        options: [{ value: "asia", label: "Asia" }, { value: "london", label: "London" }, { value: "custom", label: "Custom" }] },
      P_DIRECTION,
    ],
  }),

  // ── reversals ──
  block({
    id: "entry.rsiExtreme",
    family: "entry",
    subcategory: "reversal",
    name: "RSI Extremes",
    short: "Long when RSI < oversold / short when RSI > overbought.",
    long: "Classic mean-reversion entry. Fires when RSI crosses back inside the band (e.g. up through 30) to avoid catching falling knives.",
    userWhy: "Fades overextended moves. Pair with range / non-trend filter.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["reversal", "mean-reversion", "rsi"],
    params: [
      P_PERIOD("period", "RSI period", 14, 2, 200),
      { key: "overbought", label: "Overbought", kind: "number", default: 70,
        validation: [{ kind: "min", value: 50 }, { kind: "max", value: 100 }] },
      { key: "oversold", label: "Oversold", kind: "number", default: 30,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 50 }] },
      { key: "onReentry", label: "Fire on re-entry into the band", kind: "boolean", default: true },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.stochExtreme",
    family: "entry",
    subcategory: "reversal",
    name: "Stochastic Extremes",
    short: "%K leaves overbought / oversold.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["entry"], mt5: true, tags: ["reversal", "stochastic"],
    params: [P_PERIOD("kPeriod", "%K period", 14, 1), P_DIRECTION],
  }),
  block({
    id: "entry.bollingerMeanRev",
    family: "entry",
    subcategory: "reversal",
    name: "Bollinger Mean Reversion",
    short: "Close back inside band after touching outer band.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["entry"], mt5: true, tags: ["reversal", "bollinger", "mean-reversion"],
    params: [
      P_PERIOD("period", "Period", 20, 5),
      { key: "deviation", label: "Deviation (σ)", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 0.5 }, { kind: "step", value: 0.1 }] },
      P_DIRECTION,
    ],
  }),

  // ── zone ──
  block({
    id: "entry.supportResistance",
    family: "entry",
    subcategory: "zone",
    name: "Support / Resistance Touch",
    short: "Enter on first touch of an auto-detected S/R level.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["entry"], mt5: false, tags: ["price-action", "zone"],
    params: [P_PERIOD("lookback", "Swing lookback", 50, 10), P_DIRECTION],
  }),
  block({
    id: "entry.trendlineBreak",
    family: "entry",
    subcategory: "zone",
    name: "Trendline Break",
    short: "Break of an auto-detected swing trendline.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["entry"], mt5: false, tags: ["price-action", "zone"],
    params: [P_PERIOD("lookback", "Lookback bars", 50, 10), P_DIRECTION],
  }),

  // ── pattern triggers ──
  block({
    id: "entry.priceActionPinbar",
    family: "entry",
    subcategory: "pattern-trigger",
    name: "Pin Bar Entry",
    short: "Pin-bar reversal trigger.",
    plan: "pro", priority: "P2", complexity: "intermediate", status: "beta",
    affects: ["entry"], mt5: false, tags: ["price-action", "pattern"],
    params: [
      { key: "wickRatio", label: "Wick/body ratio", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "step", value: 0.1 }] },
      P_DIRECTION,
    ],
  }),
  block({
    id: "entry.engulfingTrigger",
    family: "entry",
    subcategory: "pattern-trigger",
    name: "Engulfing Trigger",
    short: "Bullish / bearish engulfing entry.",
    plan: "pro", priority: "P2", complexity: "intermediate", status: "beta",
    affects: ["entry"], mt5: false, tags: ["price-action", "pattern"],
    params: [P_DIRECTION],
  }),

  // ── composite ──
  block({
    id: "entry.multiSignal",
    family: "entry",
    subcategory: "composite",
    name: "Composite Signal Gate",
    short: "Require N of M sub-signals to fire simultaneously.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["entry"], mt5: false, tags: ["composite", "advanced"],
    params: [
      { key: "minRequired", label: "Minimum confirmations", kind: "integer", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 10 }] },
    ],
  }),
];
