import { block, P_PIPS, P_PERIOD } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Exit Logic (14) ──────────────────────────────────────────────────

export const EXIT_BLOCKS: BlockDefinition[] = [
  block({
    id: "exit.fixedTpSl",
    family: "exit", subcategory: "fixed", name: "Fixed TP / SL (pips)",
    short: "Hard TP and SL in pips.",
    long: "Sets take-profit and stop-loss in pips relative to entry. Simplest exit block.",
    userWhy: "Always know exactly what you're risking and targeting.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["exit"], tags: ["tp", "sl"],
    params: [
      P_PIPS("takeProfitPips", "Take profit", 30, { min: 0 }),
      P_PIPS("stopLossPips", "Stop loss", 15, { min: 0 }),
    ],
  }),
  block({
    id: "exit.fixedTpSlPrice",
    family: "exit", subcategory: "fixed", name: "Fixed TP / SL (price)",
    short: "Hard TP / SL as absolute prices.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["exit"], tags: ["tp", "sl", "price"],
    params: [
      { key: "takeProfitPrice", label: "TP price", kind: "number", default: 0,
        validation: [{ kind: "min", value: 0 }] },
      { key: "stopLossPrice", label: "SL price", kind: "number", default: 0,
        validation: [{ kind: "min", value: 0 }] },
    ],
  }),
  block({
    id: "exit.rrBased",
    family: "exit", subcategory: "rr", name: "R:R Exit",
    short: "TP = N × risk distance.",
    long: "Places TP as a multiple of the SL distance, so every trade has a defined reward:risk.",
    userWhy: "Keeps average winner / loser predictable — essential for expectancy calculations.",
    plan: "pro", priority: "P1", complexity: "basic",
    affects: ["exit"], tags: ["rr"],
    params: [
      P_PIPS("stopLossPips", "Stop loss", 20, { min: 1 }),
      { key: "rr", label: "R:R ratio", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "exit.atrBased",
    family: "exit", subcategory: "atr", name: "ATR TP / SL",
    short: "TP / SL = k × ATR.",
    long: "Uses ATR to determine SL and TP distance, so exits auto-adjust to market volatility.",
    userWhy: "Exits that scale with the market — fewer 'stopped out by noise' situations.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["exit"], mt5: true, tags: ["atr", "exit"],
    params: [
      P_PERIOD("atrPeriod", "ATR period", 14, 1),
      { key: "slMultiplier", label: "SL × ATR", kind: "number", default: 1.5,
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
      { key: "tpMultiplier", label: "TP × ATR", kind: "number", default: 3,
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "exit.timeExit",
    family: "exit", subcategory: "time", name: "Time-Based Exit",
    short: "Close after N bars or minutes.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["exit"], tags: ["time"],
    params: [
      { key: "unit", label: "Unit", kind: "select", default: "bars",
        options: [{ value: "bars", label: "Bars" }, { value: "minutes", label: "Minutes" }] },
      { key: "n", label: "Amount", kind: "integer", default: 12,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 10000 }] },
    ],
  }),
  block({
    id: "exit.endOfDay",
    family: "exit", subcategory: "time", name: "End-of-Day Exit",
    short: "Close before server day end.",
    plan: "free", priority: "P2", complexity: "basic",
    affects: ["exit"], tags: ["day"],
    params: [
      { key: "cutoffHour", label: "Cutoff hour (server)", kind: "integer", default: 22,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "max", value: 23 }] },
    ],
  }),
  block({
    id: "exit.endOfWeek",
    family: "exit", subcategory: "time", name: "End-of-Week Exit",
    short: "Flatten Friday before HH:MM.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["exit"], tags: ["weekend"],
    params: [
      { key: "cutoffHour", label: "Friday cutoff hour", kind: "integer", default: 20,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "max", value: 23 }] },
    ],
  }),
  block({
    id: "exit.oppositeSignal",
    family: "exit", subcategory: "signal", name: "Close on Opposite Signal",
    short: "Exit when entry rule fires opposite direction.",
    long: "Uses the graph's entry block (inverted) as an exit trigger. Keeps your exits consistent with your entries.",
    userWhy: "'Always in the market' style system. Great for trend-followers.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["exit"], tags: ["signal"], params: [],
  }),
  block({
    id: "exit.indicatorReversal",
    family: "exit", subcategory: "signal", name: "Indicator Reversal Exit",
    short: "Close on specified indicator flip.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["exit"], mt5: true, tags: ["exit", "signal"],
    params: [
      { key: "indicator", label: "Indicator", kind: "select", default: "ema",
        options: [{ value: "ema", label: "EMA cross" }, { value: "macd", label: "MACD cross" }, { value: "stoch", label: "Stochastic cross" }] },
    ],
  }),
  block({
    id: "exit.takeProfitLadder",
    family: "exit", subcategory: "multi", name: "TP Ladder (TP1/TP2/TP3)",
    short: "Close portions at TP1 / TP2 / TP3.",
    plan: "creator", priority: "P2", complexity: "advanced",
    affects: ["exit", "management"], tags: ["tp", "ladder"],
    params: [
      P_PIPS("tp1Pips", "TP1", 10, { min: 1 }),
      { key: "tp1Pct", label: "Close at TP1 (%)", kind: "number", default: 40,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 99 }] },
      P_PIPS("tp2Pips", "TP2", 25, { min: 1 }),
      { key: "tp2Pct", label: "Close at TP2 (%)", kind: "number", default: 40,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 99 }] },
      P_PIPS("tp3Pips", "TP3 (runner)", 60, { min: 1 }),
    ],
  }),
  block({
    id: "exit.drawdownExit",
    family: "exit", subcategory: "dd", name: "Per-Trade DD Exit",
    short: "Close at −$X or −Y pips (per trade).",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["exit"], tags: ["drawdown"],
    params: [
      { key: "maxLossDollars", label: "Max loss ($)", kind: "number", default: 50, unit: "$",
        validation: [{ kind: "min", value: 0 }] },
      P_PIPS("maxLossPips", "Max loss (pips)", 100, { min: 0 }),
    ],
  }),
  block({
    id: "exit.equityTargetExit",
    family: "exit", subcategory: "equity", name: "Daily Equity Target Exit",
    short: "Close all & stop at +X% equity for the day.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["exit", "management"], tags: ["daily", "equity"],
    params: [
      { key: "targetPercent", label: "Target (%)", kind: "number", default: 1, unit: "%",
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "exit.equityDDExit",
    family: "exit", subcategory: "equity", name: "Daily Equity DD Exit",
    short: "Close all & stop at −X% for the day.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["exit", "management"], tags: ["daily", "drawdown"],
    params: [
      { key: "maxLossPercent", label: "Max loss (%)", kind: "number", default: 2, unit: "%",
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "exit.ichimokuKijunExit",
    family: "exit", subcategory: "indicator", name: "Ichimoku Kijun Exit",
    short: "Close when price crosses Kijun.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["exit"], mt5: true, tags: ["ichimoku"],
    params: [P_PERIOD("kijun", "Kijun period", 26, 2)],
  }),
];
