import { block, P_PERIOD } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Momentum Filters (10) ────────────────────────────────────────────

export const MOMENTUM_BLOCKS: BlockDefinition[] = [
  block({
    id: "momentum.rsiBand",
    family: "momentum",
    subcategory: "oscillator",
    name: "RSI Allowed Band",
    short: "Block entries when RSI outside [low, high].",
    long: "Only allows entries when RSI sits inside a permitted band. Keeps you out of overstretched markets.",
    userWhy: "Simple noise filter — refuses trades when momentum is clearly exhausted.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["rsi", "momentum"],
    params: [
      P_PERIOD("period", "RSI period", 14, 2, 200),
      { key: "minRsi", label: "Min RSI", kind: "number", default: 30,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 100 }] },
      { key: "maxRsi", label: "Max RSI", kind: "number", default: 70,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "momentum.stochBand",
    family: "momentum",
    subcategory: "oscillator",
    name: "Stochastic Band",
    short: "Same as RSI band, for %K.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["stochastic"],
    params: [
      P_PERIOD("kPeriod", "%K period", 14, 1),
      { key: "minK", label: "Min %K", kind: "number", default: 20 },
      { key: "maxK", label: "Max %K", kind: "number", default: 80 },
    ],
  }),
  block({
    id: "momentum.cciBand",
    family: "momentum",
    subcategory: "oscillator",
    name: "CCI Band",
    short: "CCI allowed range.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["cci"],
    params: [
      P_PERIOD("period", "CCI period", 20, 2),
      { key: "minCci", label: "Min CCI", kind: "number", default: -100 },
      { key: "maxCci", label: "Max CCI", kind: "number", default: 100 },
    ],
  }),
  block({
    id: "momentum.williamsR",
    family: "momentum",
    subcategory: "oscillator",
    name: "Williams %R",
    short: "Williams %R allowed range.",
    plan: "creator", priority: "P3", complexity: "basic", status: "beta",
    affects: ["filter"], mt5: true, tags: ["williamsR"],
    params: [P_PERIOD("period", "Period", 14, 2)],
  }),
  block({
    id: "momentum.rocThreshold",
    family: "momentum",
    subcategory: "oscillator",
    name: "Rate of Change",
    short: "Absolute ROC > / < threshold.",
    long: "Checks the N-period rate-of-change and rejects entries where momentum is weak (or where it's too strong, if inverted).",
    userWhy: "Fast way to demand minimum thrust before entering.",
    plan: "pro", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["momentum", "roc"],
    params: [
      P_PERIOD("period", "ROC period", 10, 1),
      { key: "threshold", label: "Threshold (%)", kind: "number", default: 0.2, unit: "%",
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "step", value: 0.05 }] },
      { key: "direction", label: "Require", kind: "select", default: "above",
        options: [{ value: "above", label: "ROC magnitude above threshold" }, { value: "below", label: "ROC magnitude below threshold" }] },
    ],
  }),
  block({
    id: "momentum.macdHist",
    family: "momentum",
    subcategory: "histogram",
    name: "MACD Histogram Size",
    short: "Abs histogram above threshold.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["macd"],
    params: [
      P_PERIOD("fastPeriod", "Fast EMA", 12, 2),
      P_PERIOD("slowPeriod", "Slow EMA", 26, 2),
      P_PERIOD("signalPeriod", "Signal", 9, 1),
      { key: "minHist", label: "Min |histogram|", kind: "number", default: 0.0002,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }] },
    ],
  }),
  block({
    id: "momentum.rsiDivergence",
    family: "momentum",
    subcategory: "divergence",
    name: "RSI Divergence",
    short: "Regular / hidden RSI divergence.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["filter"], mt5: true, tags: ["divergence", "rsi"],
    params: [P_PERIOD("period", "RSI period", 14, 2), P_PERIOD("lookback", "Divergence lookback", 20, 5)],
  }),
  block({
    id: "momentum.macdDivergence",
    family: "momentum",
    subcategory: "divergence",
    name: "MACD Divergence",
    short: "MACD divergence detector.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["filter"], mt5: true, tags: ["divergence", "macd"],
    params: [P_PERIOD("lookback", "Divergence lookback", 20, 5)],
  }),
  block({
    id: "momentum.momentumIndex",
    family: "momentum",
    subcategory: "oscillator",
    name: "Momentum Index",
    short: "Close / close-N > 1 long; < 1 short.",
    plan: "free", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["momentum"],
    params: [P_PERIOD("period", "Period", 10, 1)],
  }),
  block({
    id: "momentum.trix",
    family: "momentum",
    subcategory: "oscillator",
    name: "TRIX Side",
    short: "TRIX above / below zero.",
    plan: "creator", priority: "P3", complexity: "intermediate", status: "beta",
    affects: ["filter"], mt5: true, tags: ["trix"],
    params: [P_PERIOD("period", "Period", 15, 2)],
  }),
];
