import { block, P_PERIOD, P_TIMEFRAME } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Trend Filters (12) ───────────────────────────────────────────────

export const TREND_BLOCKS: BlockDefinition[] = [
  block({
    id: "trend.emaSlope",
    family: "trend",
    subcategory: "slope",
    name: "EMA Slope Filter",
    short: "Slope of EMA(N) must match direction.",
    long: "Computes the EMA slope over `lookback` bars and blocks trades that fight it. A clean way to stay trend-aligned.",
    userWhy: "Keeps you out of counter-trend trades by requiring the MA to be moving your way.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["trend", "ema", "slope"],
    params: [
      P_PERIOD("period", "EMA period", 50, 2),
      { key: "lookback", label: "Slope lookback (bars)", kind: "integer", default: 5,
        validation: [{ kind: "required" }, { kind: "min", value: 2 }, { kind: "max", value: 50 }] },
    ],
  }),
  block({
    id: "trend.smaDirection",
    family: "trend",
    subcategory: "slope",
    name: "SMA Direction",
    short: "SMA rising / falling.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["trend", "sma"],
    params: [P_PERIOD("period", "SMA period", 100, 2), P_PERIOD("lookback", "Slope lookback", 5, 2)],
  }),
  block({
    id: "trend.adxStrength",
    family: "trend",
    subcategory: "strength",
    name: "ADX Trend Strength",
    short: "ADX must exceed a threshold.",
    long: "Requires ADX above a minimum value — only trade when a trend is actually present. Standard value is 20–25.",
    userWhy: "Stops a trend-following system from taking trades in flat markets.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["trend", "adx", "regime"],
    params: [
      P_PERIOD("period", "ADX period", 14, 2),
      { key: "minAdx", label: "Minimum ADX", kind: "number", default: 20,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "trend.adxNonTrend",
    family: "trend",
    subcategory: "strength",
    name: "ADX Non-Trend",
    short: "ADX below a threshold — ranging only.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["range", "adx"],
    params: [
      P_PERIOD("period", "ADX period", 14, 2),
      { key: "maxAdx", label: "Maximum ADX", kind: "number", default: 20,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "trend.higherTfEma",
    family: "trend",
    subcategory: "mtf",
    name: "Higher-TF EMA Alignment",
    short: "Higher-TF EMA slope must agree.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["trend", "mtf"],
    params: [P_TIMEFRAME("timeframe", "Higher timeframe", "H4"), P_PERIOD("period", "EMA period", 50, 2)],
  }),
  block({
    id: "trend.ichimokuCloudSide",
    family: "trend",
    subcategory: "cloud",
    name: "Price vs Ichimoku Cloud",
    short: "Price above / below the Kumo.",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: true, tags: ["ichimoku"],
    params: [P_PERIOD("tenkan", "Tenkan", 9, 1), P_PERIOD("kijun", "Kijun", 26, 1), P_PERIOD("senkou", "Senkou", 52, 1)],
  }),
  block({
    id: "trend.hullDirection",
    family: "trend",
    subcategory: "slope",
    name: "Hull MA Direction",
    short: "HMA rising / falling.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["hma"],
    params: [P_PERIOD("period", "HMA period", 55, 2)],
  }),
  block({
    id: "trend.supertrend",
    family: "trend",
    subcategory: "flip",
    name: "Supertrend Side",
    short: "Price relative to Supertrend line.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["supertrend"],
    params: [
      P_PERIOD("atrPeriod", "ATR period", 10, 1),
      { key: "multiplier", label: "Multiplier", kind: "number", default: 3,
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "trend.parabolicSar",
    family: "trend",
    subcategory: "flip",
    name: "Parabolic SAR Side",
    short: "SAR dots below (long-ok) / above (short-ok).",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["sar"],
    params: [
      { key: "step", label: "Step", kind: "number", default: 0.02,
        validation: [{ kind: "required" }, { kind: "min", value: 0.001 }, { kind: "step", value: 0.001 }] },
      { key: "maxStep", label: "Max step", kind: "number", default: 0.2,
        validation: [{ kind: "required" }, { kind: "min", value: 0.01 }] },
    ],
  }),
  block({
    id: "trend.aroon",
    family: "trend",
    subcategory: "strength",
    name: "Aroon Trend",
    short: "Aroon-Up vs Aroon-Down dominance.",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: true, tags: ["aroon"],
    params: [P_PERIOD("period", "Aroon period", 14, 2)],
  }),
  block({
    id: "trend.dmiDirection",
    family: "trend",
    subcategory: "strength",
    name: "DMI Direction",
    short: "+DI vs −DI dominance.",
    plan: "pro", priority: "P3", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["dmi", "adx"],
    params: [P_PERIOD("period", "DMI period", 14, 2)],
  }),
  block({
    id: "trend.linearRegression",
    family: "trend",
    subcategory: "slope",
    name: "Linear Regression Slope",
    short: "Sign of N-bar linear-regression slope.",
    plan: "creator", priority: "P3", complexity: "advanced",
    affects: ["filter"], mt5: true, tags: ["regression"],
    params: [P_PERIOD("period", "Regression bars", 50, 5)],
  }),
];
