import { block } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Utility / Trade Constraints (12) ─────────────────────────────────

export const UTILITY_BLOCKS: BlockDefinition[] = [
  block({
    id: "utility.oneTradeAtTime",
    family: "utility", subcategory: "count", name: "One Trade At A Time",
    short: "No new trades while one is open.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], tags: ["constraint"], params: [],
  }),
  block({
    id: "utility.maxOpenPositions",
    family: "utility", subcategory: "count", name: "Max Open Positions",
    short: "Hard cap on simultaneous positions.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], tags: ["constraint"],
    params: [
      { key: "maxPositions", label: "Max positions", kind: "integer", default: 3,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "utility.maxDailyTrades",
    family: "utility", subcategory: "count", name: "Max Daily Trades",
    short: "Stop opening after N trades today.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], tags: ["constraint", "daily"],
    params: [
      { key: "maxTrades", label: "Max trades / day", kind: "integer", default: 5,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 500 }] },
    ],
  }),
  block({
    id: "utility.maxDailyLoss",
    family: "utility", subcategory: "risk-gate", name: "Max Daily Loss (%)",
    short: "Pause for the day after −X% equity.",
    long: "Monitors realised P/L for the day; once the threshold is hit, opens no new trades until the next server day.",
    userWhy: "Prop-firm compatible. Saves users from revenge-trading.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["filter"], tags: ["daily", "risk"],
    params: [
      { key: "maxLossPercent", label: "Max daily loss (%)", kind: "number", default: 3, unit: "%",
        validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "max", value: 50 }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "utility.maxWeeklyLoss",
    family: "utility", subcategory: "risk-gate", name: "Max Weekly Loss",
    short: "Mirror, weekly window.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], tags: ["weekly", "risk"],
    params: [{ key: "maxLossPercent", label: "Max weekly loss (%)", kind: "number", default: 8, unit: "%",
      validation: [{ kind: "required" }, { kind: "min", value: 0.1 }, { kind: "max", value: 100 }, { kind: "step", value: 0.1 }] }],
  }),
  block({
    id: "utility.maxConsecutiveLosses",
    family: "utility", subcategory: "behaviour", name: "Max Consecutive Losses",
    short: "Pause after N losses in a row.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], tags: ["behaviour"],
    params: [
      { key: "maxLosses", label: "Max losses", kind: "integer", default: 3,
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 20 }] },
    ],
  }),
  block({
    id: "utility.emergencyStop",
    family: "utility", subcategory: "emergency", name: "Emergency Equity Stop",
    short: "Flatten all when equity drops past threshold.",
    long: "Hard kill-switch. Watches equity against a floor or a max-drawdown ceiling and closes everything when either breaches.",
    userWhy: "Non-negotiable for grid / martingale users. Useful guardrail for everyone.",
    plan: "pro", priority: "P1", complexity: "intermediate",
    affects: ["management", "exit"], tags: ["emergency"],
    params: [
      { key: "mode", label: "Mode", kind: "select", default: "drawdown",
        options: [{ value: "drawdown", label: "Max drawdown from peak (%)" }, { value: "floor", label: "Equity floor ($)" }] },
      { key: "maxDrawdownPercent", label: "Max drawdown (%)", kind: "number", default: 10, unit: "%",
        visibleWhen: { key: "mode", equals: "drawdown" },
        validation: [{ kind: "min", value: 0.1 }, { kind: "max", value: 99 }, { kind: "step", value: 0.1 }] },
      { key: "equityFloor", label: "Equity floor ($)", kind: "number", default: 0, unit: "$",
        visibleWhen: { key: "mode", equals: "floor" },
        validation: [{ kind: "min", value: 0 }] },
    ],
  }),
  block({
    id: "utility.maxSpread",
    family: "utility", subcategory: "execution", name: "Global Max Spread",
    short: "Global spread cap — applies everywhere.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], tags: ["spread"],
    params: [{ key: "maxSpreadPoints", label: "Max spread (points)", kind: "integer", default: 40,
      validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 10000 }] }],
  }),
  block({
    id: "utility.minBalance",
    family: "utility", subcategory: "account", name: "Minimum Balance",
    short: "Refuse to trade under balance floor.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], tags: ["balance"],
    params: [{ key: "floor", label: "Balance floor ($)", kind: "number", default: 100, unit: "$",
      validation: [{ kind: "required" }, { kind: "min", value: 0 }] }],
  }),
  block({
    id: "utility.onlyNewBar",
    family: "utility", subcategory: "tick", name: "Only On New Bar",
    short: "Run entry logic once per bar.",
    long: "Prevents the entry rule from re-evaluating on every tick. Almost always desired — many strategies misbehave without it.",
    userWhy: "Stops intra-bar flipping and flicker. Usually a free accuracy boost.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], tags: ["tick"], params: [],
  }),
  block({
    id: "utility.cooldownAfterSl",
    family: "utility", subcategory: "behaviour", name: "Cooldown After SL",
    short: "Pause N minutes after SL hit.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], tags: ["cooldown"],
    params: [{ key: "minutes", label: "Cooldown (min)", kind: "integer", default: 30, unit: "min",
      validation: [{ kind: "required" }, { kind: "min", value: 1 }] }],
  }),
  block({
    id: "utility.cooldownAfterTp",
    family: "utility", subcategory: "behaviour", name: "Cooldown After TP",
    short: "Pause N minutes after TP hit.",
    plan: "pro", priority: "P3", complexity: "basic", status: "beta",
    affects: ["filter"], tags: ["cooldown"],
    params: [{ key: "minutes", label: "Cooldown (min)", kind: "integer", default: 15, unit: "min",
      validation: [{ kind: "required" }, { kind: "min", value: 1 }] }],
  }),
];
