import { block, P_PERIOD, P_PIPS } from "../_factory";
import type { BlockDefinition } from "../types";

// ── Volatility Filters (10) ──────────────────────────────────────────

export const VOLATILITY_BLOCKS: BlockDefinition[] = [
  block({
    id: "vol.atrBand",
    family: "volatility",
    subcategory: "atr",
    name: "ATR Allowed Range",
    short: "ATR(period) must be within [min, max] pips.",
    long: "Rejects entries when ATR is too low (chop) or too high (news spike). A single block that covers the majority of volatility filters users need.",
    userWhy: "Stops you trading in dead markets AND in gappy markets.",
    plan: "free", priority: "P1", complexity: "basic",
    affects: ["filter"], mt5: true, tags: ["atr", "volatility"],
    params: [
      P_PERIOD("period", "ATR period", 14, 1),
      P_PIPS("minAtrPips", "Min ATR", 5),
      P_PIPS("maxAtrPips", "Max ATR", 300),
    ],
  }),
  block({
    id: "vol.atrAboveAverage",
    family: "volatility",
    subcategory: "atr",
    name: "ATR Above Its Average",
    short: "ATR above N-period ATR MA.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["atr", "regime"],
    params: [P_PERIOD("atrPeriod", "ATR period", 14, 1), P_PERIOD("maPeriod", "ATR-MA period", 50, 2)],
  }),
  block({
    id: "vol.atrBelowAverage",
    family: "volatility",
    subcategory: "atr",
    name: "ATR Below Its Average",
    short: "ATR below its N-period average.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["atr", "regime"],
    params: [P_PERIOD("atrPeriod", "ATR period", 14, 1), P_PERIOD("maPeriod", "ATR-MA period", 50, 2)],
  }),
  block({
    id: "vol.bbWidth",
    family: "volatility",
    subcategory: "bands",
    name: "Bollinger Bandwidth",
    short: "BB width above / below threshold.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: true, tags: ["bollinger", "squeeze"],
    params: [
      P_PERIOD("period", "Period", 20, 5),
      { key: "deviation", label: "Deviation (σ)", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "min", value: 0.5 }, { kind: "step", value: 0.1 }] },
      { key: "widthThreshold", label: "Width threshold", kind: "number", default: 0.004,
        validation: [{ kind: "required" }, { kind: "min", value: 0 }, { kind: "step", value: 0.0001 }] },
      { key: "mode", label: "Mode", kind: "select", default: "above",
        options: [{ value: "above", label: "Width above threshold (expansion)" }, { value: "below", label: "Width below threshold (squeeze)" }] },
    ],
  }),
  block({
    id: "vol.keltnerInside",
    family: "volatility",
    subcategory: "bands",
    name: "Inside Keltner Channel",
    short: "Price inside Keltner channel (squeeze).",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["filter"], mt5: true, tags: ["keltner", "squeeze"],
    params: [
      P_PERIOD("emaPeriod", "EMA period", 20, 2),
      P_PERIOD("atrPeriod", "ATR period", 10, 1),
      { key: "multiplier", label: "ATR multiplier", kind: "number", default: 2,
        validation: [{ kind: "required" }, { kind: "step", value: 0.1 }] },
    ],
  }),
  block({
    id: "vol.stdDevThreshold",
    family: "volatility",
    subcategory: "statistical",
    name: "Std-Dev Threshold",
    short: "Close-to-close σ above / below threshold.",
    plan: "creator", priority: "P3", complexity: "intermediate", status: "beta",
    affects: ["filter"], mt5: true, tags: ["statistical"],
    params: [P_PERIOD("period", "Period", 20, 2)],
  }),
  block({
    id: "vol.dailyRange",
    family: "volatility",
    subcategory: "range-used",
    name: "Daily Range Used",
    short: "Block after N% of typical daily range is used.",
    plan: "pro", priority: "P2", complexity: "intermediate",
    affects: ["filter"], mt5: false, tags: ["range", "session"],
    params: [
      { key: "maxPercent", label: "Max % of daily range used", kind: "number", default: 70, unit: "%",
        validation: [{ kind: "required" }, { kind: "min", value: 1 }, { kind: "max", value: 100 }] },
    ],
  }),
  block({
    id: "vol.volatilityRatio",
    family: "volatility",
    subcategory: "atr",
    name: "Short/Long ATR Ratio",
    short: "ATR(fast) / ATR(slow) thresholded.",
    plan: "creator", priority: "P3", complexity: "advanced", status: "beta",
    affects: ["filter"], mt5: true, tags: ["atr", "regime"],
    params: [P_PERIOD("fastPeriod", "Fast ATR", 7, 1), P_PERIOD("slowPeriod", "Slow ATR", 50, 2)],
  }),
  block({
    id: "vol.gapFilter",
    family: "volatility",
    subcategory: "event",
    name: "Overnight Gap Filter",
    short: "Block if bar gapped > k pips.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: false, tags: ["gap"],
    params: [P_PIPS("maxGapPips", "Max gap", 30)],
  }),
  block({
    id: "vol.weekendCarry",
    family: "volatility",
    subcategory: "event",
    name: "Weekend Carry Filter",
    short: "Block entries Fri after HH:MM.",
    plan: "pro", priority: "P2", complexity: "basic",
    affects: ["filter"], mt5: false, tags: ["weekend"],
    params: [
      { key: "cutoffHour", label: "Friday cutoff hour (server)", kind: "integer", default: 20,
        validation: [{ kind: "min", value: 0 }, { kind: "max", value: 23 }] },
    ],
  }),
];
