"use client";

// Client-side helper: bundle a marketplace EA (.mq5 source) with any
// attached setfiles into a single ZIP. Used by the listing detail page
// at download time for paid buyers and free-tier Get flows.

import JSZip from "jszip";
import { fetchSetfileBlob, listSetfilesForListing, type SetfileRow } from "./client";

export interface BundleInput {
  listingId: string;
  eaFilename: string;   // e.g. "USDJPY_Scalper_Pro.mq5"
  eaSource: string;     // the MQL5 source text
  extraReadme?: string; // optional text file contents
}

export interface BundleResult {
  blob: Blob;
  filename: string;
  includedSetfiles: number;
}

/**
 * Build a ZIP blob containing the EA + every attached setfile. When no
 * setfiles are attached we still return a zip with just the .mq5 (keeps
 * the download UX uniform).
 */
export async function buildListingBundle(input: BundleInput): Promise<BundleResult> {
  const zip = new JSZip();
  zip.file(input.eaFilename, input.eaSource);

  let included = 0;
  try {
    const setfiles = await listSetfilesForListing(input.listingId);
    if (setfiles.length > 0) {
      const folder = zip.folder("setfiles");
      if (folder) {
        for (const row of setfiles) {
          const blob = await fetchSetfileBlob(row);
          if (!blob) continue;
          const ext = (row.file_path.match(/\.[a-zA-Z0-9]+$/)?.[0]) ?? ".set";
          const safeName = sanitizeFilename(row.name) + ext;
          folder.file(safeName, blob);
          included++;
        }
        // Index file so humans know what each set maps to.
        folder.file(
          "README.txt",
          buildSetfilesReadme(setfiles),
        );
      }
    }
  } catch {
    // Setfiles are optional — if listing has none or RLS blocks a public
    // read, we still ship the .mq5 on its own.
  }

  if (input.extraReadme) {
    zip.file("README.txt", input.extraReadme);
  }

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
  const baseName = input.eaFilename.replace(/\.mq5$/i, "");
  return {
    blob,
    filename: `${baseName}.zip`,
    includedSetfiles: included,
  };
}

function sanitizeFilename(name: string): string {
  return name.replace(/[\\/:*?"<>|]+/g, "_").replace(/\s+/g, "_").slice(0, 60) || "setfile";
}

function buildSetfilesReadme(rows: SetfileRow[]): string {
  const lines = [
    "Setfiles included with this EA.",
    "Generated by Zentryx Lab — https://lab.zentryx.tech",
    "",
  ];
  for (const r of rows) {
    lines.push(`• ${r.name}`);
    const meta = [
      r.symbol    ? `symbol: ${r.symbol}`       : null,
      r.timeframe ? `timeframe: ${r.timeframe}` : null,
      r.broker    ? `broker: ${r.broker}`       : null,
    ].filter(Boolean).join(" · ");
    if (meta) lines.push(`  ${meta}`);
    if (r.description) lines.push(`  ${r.description.replace(/\r?\n/g, " ")}`);
    lines.push("");
  }
  return lines.join("\n");
}
