import type { SectionContribution, SignalDirection } from "./types";
import type { StrategyGraph } from "@/lib/strategies/types";

interface AssemblerInput {
  eaName: string;
  graph: StrategyGraph;
  contributions: SectionContribution[];
}

// ──────────────────────────────────────────────────────────────────
// Template assembler
// ──────────────────────────────────────────────────────────────────
// Takes the merged contributions from every translator and emits a
// single, valid MQL5 source file. Sections are deterministic so the
// same graph always produces byte-identical output.
// ──────────────────────────────────────────────────────────────────

export function assemble(input: AssemblerInput): string {
  const { eaName, graph, contributions } = input;
  const inputs = mergeInputs(contributions);
  const indicators = mergeIndicators(contributions);
  const helpers = mergeHelpers(contributions);
  const globals = mergeGlobals(contributions);
  const gates = mergeGates(contributions);
  const longExpr = combineEntry(contributions, "long");
  const shortExpr = combineEntry(contributions, "short");
  const lotExpr = pickSingle(contributions, "lotExpr") ?? "NormalizeLots(0.01)";
  const stopBody = pickSingleStop(contributions);
  const positionMgmt = mergePositionMgmt(contributions);
  const onInitExtra = mergeStringList(contributions, "onInitCode");
  const onDeinitExtra = mergeStringList(contributions, "onDeinitCode");

  const sym = graph.metadata.symbol ?? "EURUSD";
  const tf = graph.metadata.timeframe ?? "M15";
  const magic = graph.metadata.magicNumber ?? 20260418;

  return `//+------------------------------------------------------------------+
//|  ${escapeComment(eaName)}.mq5
//|  Generated by Zentryx Lab on ${new Date().toISOString()}
//|  Source-of-truth: visual strategy graph. Do not hand-edit.
//+------------------------------------------------------------------+
#property copyright "Generated by Zentryx Lab"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

//─────────────────────────────────────────────────────────────────────
// Inputs
//─────────────────────────────────────────────────────────────────────
input string  InpSymbolHint = "${sym}";        // Symbol hint (informational)
input ENUM_TIMEFRAMES InpTimeframe = ${timeframeEnum(tf)};   // Working timeframe
input long    InpMagic       = ${magic};        // Magic number
input string  InpTradeComment = "${escapeStr(graph.metadata.tradeComment ?? "Zentryx Lab")}"; // Trade comment
${inputsBlock(inputs)}

//─────────────────────────────────────────────────────────────────────
// Indicator handles
//─────────────────────────────────────────────────────────────────────
${indicators.map((h) => `int ${h.handleVar} = INVALID_HANDLE;`).join("\n")}

//─────────────────────────────────────────────────────────────────────
// Globals
//─────────────────────────────────────────────────────────────────────
CTrade Trade;
${globals.length ? globals.join("\n\n") : "// (no extra globals)"}

//─────────────────────────────────────────────────────────────────────
// Helpers
//─────────────────────────────────────────────────────────────────────
double ZxPipSize()
{
   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   return (digits == 3 || digits == 5) ? point * 10.0 : point;
}

double NormalizeLots(double lots)
{
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(lotStep <= 0) lotStep = 0.01;
   double normalized = MathFloor(lots / lotStep) * lotStep;
   if(normalized < minLot) normalized = minLot;
   if(normalized > maxLot) normalized = maxLot;
   return NormalizeDouble(normalized, 2);
}

double BufferValue(int handle, int shift)
{
   if(handle == INVALID_HANDLE) return 0.0;
   double buf[];
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return 0.0;
   return buf[0];
}

void ZxModifySL(double newSl)
{
   if(!PositionSelect(_Symbol)) return;
   double tp = PositionGetDouble(POSITION_TP);
   Trade.PositionModify(_Symbol, NormalizeDouble(newSl, _Digits), tp);
}

bool ZxIsNewBar()
{
   static datetime lastBar = 0;
   datetime cur = iTime(_Symbol, _Period, 0);
   if(cur != lastBar) { lastBar = cur; return true; }
   return false;
}

${helpers.length ? helpers.join("\n\n") : ""}

//─────────────────────────────────────────────────────────────────────
// Lifecycle
//─────────────────────────────────────────────────────────────────────
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagic);
${indent(indicators.map((h) => h.init).join("\n"), 3)}

   ${indicators.length
     ? `if(${indicators.map((h) => `${h.handleVar} == INVALID_HANDLE`).join(" || ")})
   {
      Print("Failed to create indicator handle(s).");
      return INIT_FAILED;
   }`
     : "// no indicators"}
${indent(onInitExtra.join("\n"), 3)}
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
${indent(indicators.map((h) => h.release).join("\n"), 3)}
${indent(onDeinitExtra.join("\n"), 3)}
}

//─────────────────────────────────────────────────────────────────────
// Tick / bar processing
//─────────────────────────────────────────────────────────────────────
void OnTick()
{
   // 1. Manage open position first (trailing, break-even, etc.)
${indent(positionMgmt.length ? positionMgmt.join("\n") : "// no position management", 3)}

   // 2. New bar gating: most logic only fires once per bar
   if(!ZxIsNewBar()) return;

   // 3. Pre-trade gates
${indent(
  gates.length
    ? gates.map((g) => `if(!${g.expr}) return; // ${escapeComment(g.reason)}`).join("\n")
    : "// no gates",
  3,
)}

   // 4. Entry signals
   bool wantLong  = ${longExpr};
   bool wantShort = ${shortExpr};

   if(wantLong && !PositionSelect(_Symbol))  ZxOpen(ORDER_TYPE_BUY);
   if(wantShort && !PositionSelect(_Symbol)) ZxOpen(ORDER_TYPE_SELL);
}

//─────────────────────────────────────────────────────────────────────
// Order entry
//─────────────────────────────────────────────────────────────────────
void ZxOpen(ENUM_ORDER_TYPE direction)
{
   double entryPrice = (direction == ORDER_TYPE_BUY)
                       ? SymbolInfoDouble(_Symbol, SYMBOL_ASK)
                       : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double slPrice = 0.0;
   double tpPrice = 0.0;

${indent(stopBody, 3)}

   double lots = ${lotExpr};
   if(lots <= 0) { Print("Computed lot size <= 0; skipping entry."); return; }

   if(direction == ORDER_TYPE_BUY)
      Trade.Buy(lots, _Symbol, entryPrice,
                NormalizeDouble(slPrice, _Digits),
                NormalizeDouble(tpPrice, _Digits),
                InpTradeComment);
   else
      Trade.Sell(lots, _Symbol, entryPrice,
                 NormalizeDouble(slPrice, _Digits),
                 NormalizeDouble(tpPrice, _Digits),
                 InpTradeComment);
}
`;
}

// ───────────────── helpers ─────────────────

function mergeInputs(cs: SectionContribution[]) {
  const seen = new Map<string, ReturnType<() => SectionContribution>["inputs"] extends infer T ? T : never>();
  const out: NonNullable<SectionContribution["inputs"]> = [];
  for (const c of cs) {
    for (const inp of c.inputs ?? []) {
      if (seen.has(inp.name)) continue;
      seen.set(inp.name, undefined as never);
      out.push(inp);
    }
  }
  return out;
}

function mergeIndicators(cs: SectionContribution[]) {
  const seen = new Set<string>();
  const out: NonNullable<SectionContribution["indicators"]> = [];
  for (const c of cs) {
    for (const ind of c.indicators ?? []) {
      if (seen.has(ind.handleVar)) continue;
      seen.add(ind.handleVar);
      out.push(ind);
    }
  }
  return out;
}

function mergeHelpers(cs: SectionContribution[]) {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const c of cs) {
    for (const h of c.helpers ?? []) {
      if (seen.has(h)) continue;
      seen.add(h);
      out.push(h);
    }
  }
  return out;
}

function mergeGlobals(cs: SectionContribution[]) {
  const out: string[] = [];
  for (const c of cs) for (const g of c.globals ?? []) out.push(g);
  return out;
}

function mergeGates(cs: SectionContribution[]) {
  const out: { expr: string; reason: string }[] = [];
  for (const c of cs) for (const g of c.gates ?? []) out.push(g);
  return out;
}

function mergePositionMgmt(cs: SectionContribution[]) {
  const out: string[] = [];
  for (const c of cs) for (const m of c.positionManagement ?? []) out.push(m);
  return out;
}

function mergeStringList(
  cs: SectionContribution[],
  key: "onInitCode" | "onDeinitCode",
): string[] {
  const out: string[] = [];
  for (const c of cs) for (const m of c[key] ?? []) out.push(m);
  return out;
}

function combineEntry(cs: SectionContribution[], dir: SignalDirection): string {
  const exprs: string[] = [];
  for (const c of cs) {
    for (const cond of c.entryConditions ?? []) {
      if (cond.direction === dir || cond.direction === "both") {
        exprs.push(cond.expr);
      }
    }
  }
  if (exprs.length === 0) return "false";
  return exprs.join("\n               && ");
}

function pickSingle<K extends keyof SectionContribution>(
  cs: SectionContribution[],
  key: K,
): SectionContribution[K] | undefined {
  for (const c of cs) if (c[key] !== undefined) return c[key];
  return undefined;
}

function pickSingleStop(cs: SectionContribution[]): string {
  for (const c of cs) if (c.stopLevels) return c.stopLevels.body;
  // Default: no SL/TP
  return "// no stop levels configured\nslPrice = 0.0; tpPrice = 0.0;";
}

function inputsBlock(inputs: NonNullable<SectionContribution["inputs"]>): string {
  if (inputs.length === 0) return "// (no node inputs)";
  return inputs
    .map((i) => `input ${i.type} ${i.name} = ${i.defaultExpr};${i.label ? ` // ${i.label}` : ""}`)
    .join("\n");
}

function indent(text: string, spaces: number): string {
  if (!text) return "";
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, "* /");
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function timeframeEnum(tf: string): string {
  const map: Record<string, string> = {
    M1: "PERIOD_M1", M5: "PERIOD_M5", M15: "PERIOD_M15", M30: "PERIOD_M30",
    H1: "PERIOD_H1", H4: "PERIOD_H4", D1: "PERIOD_D1", W1: "PERIOD_W1", MN1: "PERIOD_MN1",
  };
  return map[tf] ?? "PERIOD_CURRENT";
}
