import type { SectionContribution, SignalDirection, CompileOptions } from "./types";
import type { StrategyGraph } from "@/lib/strategies/types";

interface AssemblerInput {
  eaName: string;
  graph: StrategyGraph;
  contributions: SectionContribution[];
  telemetry?: CompileOptions["telemetry"];
}

// ──────────────────────────────────────────────────────────────────
// Template assembler
// ──────────────────────────────────────────────────────────────────
// Takes the merged contributions from every translator and emits a
// single, valid MQL5 source file. Sections are deterministic so the
// same graph always produces byte-identical output.
// ──────────────────────────────────────────────────────────────────

export function assemble(input: AssemblerInput): string {
  const { eaName, graph, contributions, telemetry } = input;
  const inputs = mergeInputs(contributions);
  const indicators = mergeIndicators(contributions);
  const helpers = mergeHelpers(contributions);
  const globals = mergeGlobals(contributions);
  const gates = mergeGates(contributions);
  const longExpr = combineEntry(contributions, "long");
  const shortExpr = combineEntry(contributions, "short");
  const lotExpr = pickSingle(contributions, "lotExpr") ?? "NormalizeLots(0.01)";
  const stopBody = pickSingleStop(contributions);
  const positionMgmt = mergePositionMgmt(contributions);
  const onInitExtra = mergeStringList(contributions, "onInitCode");
  const onDeinitExtra = mergeStringList(contributions, "onDeinitCode");

  const sym = graph.metadata.symbol ?? "EURUSD";
  const tf = graph.metadata.timeframe ?? "M15";
  const magic = graph.metadata.magicNumber ?? 20260418;

  const telemetryEnabled = Boolean(telemetry?.token && telemetry?.endpoint);
  const telemetryUrl = telemetry?.endpoint ?? "";
  const telemetryToken = telemetry?.token ?? "";
  const telemetryHeader = telemetryEnabled ? telemetryInputsBlock() : "";
  const telemetryHelpers = telemetryEnabled ? telemetryHelpersBlock() : "";
  const telemetryHandler = telemetryEnabled ? telemetryHandlerBlock() : "";

  return `//+------------------------------------------------------------------+
//|  ${escapeComment(eaName)}.mq5
//|  Generated by Zentryx Lab on ${new Date().toISOString()}
//|  Source-of-truth: visual strategy graph. Do not hand-edit.
//+------------------------------------------------------------------+
#property copyright "Generated by Zentryx Lab"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>

//─────────────────────────────────────────────────────────────────────
// Inputs
//─────────────────────────────────────────────────────────────────────
input string  InpSymbolHint = "${sym}";        // Symbol hint (informational)
input ENUM_TIMEFRAMES InpTimeframe = ${timeframeEnum(tf)};   // Working timeframe
input long    InpMagic       = ${magic};        // Magic number
input string  InpTradeComment = "${escapeStr(graph.metadata.tradeComment ?? "Zentryx Lab")}"; // Trade comment
${telemetryHeader ? `
// ── Live telemetry (Zentryx Lab) ───────────────────────────────────
input string  InpTelemetryUrl   = "${escapeStr(telemetryUrl)}";
input string  InpTelemetryToken = "${escapeStr(telemetryToken)}";
input bool    InpTelemetryOn    = true;          // Report closed trades to Zentryx Lab
` : ""}${inputsBlock(inputs)}

//─────────────────────────────────────────────────────────────────────
// Indicator handles
//─────────────────────────────────────────────────────────────────────
${indicators.map((h) => `int ${h.handleVar} = INVALID_HANDLE;`).join("\n")}

//─────────────────────────────────────────────────────────────────────
// Globals
//─────────────────────────────────────────────────────────────────────
CTrade Trade;
${globals.length ? globals.join("\n\n") : "// (no extra globals)"}

//─────────────────────────────────────────────────────────────────────
// Helpers
//─────────────────────────────────────────────────────────────────────
double ZxPipSize()
{
   double point  = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   return (digits == 3 || digits == 5) ? point * 10.0 : point;
}

double NormalizeLots(double lots)
{
   double minLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(lotStep <= 0) lotStep = 0.01;
   double normalized = MathFloor(lots / lotStep) * lotStep;
   if(normalized < minLot) normalized = minLot;
   if(normalized > maxLot) normalized = maxLot;
   return NormalizeDouble(normalized, 2);
}

double BufferValue(int handle, int shift)
{
   if(handle == INVALID_HANDLE) return 0.0;
   double buf[];
   if(CopyBuffer(handle, 0, shift, 1, buf) <= 0) return 0.0;
   return buf[0];
}

void ZxModifySL(double newSl)
{
   if(!PositionSelect(_Symbol)) return;
   double tp = PositionGetDouble(POSITION_TP);
   Trade.PositionModify(_Symbol, NormalizeDouble(newSl, _Digits), tp);
}

bool ZxIsNewBar()
{
   static datetime lastBar = 0;
   datetime cur = iTime(_Symbol, _Period, 0);
   if(cur != lastBar) { lastBar = cur; return true; }
   return false;
}

${helpers.length ? helpers.join("\n\n") : ""}
${telemetryHelpers}

//─────────────────────────────────────────────────────────────────────
// Lifecycle
//─────────────────────────────────────────────────────────────────────
int OnInit()
{
   Trade.SetExpertMagicNumber(InpMagic);
${indent(indicators.map((h) => h.init).join("\n"), 3)}

   ${indicators.length
     ? `if(${indicators.map((h) => `${h.handleVar} == INVALID_HANDLE`).join(" || ")})
   {
      Print("Failed to create indicator handle(s).");
      return INIT_FAILED;
   }`
     : "// no indicators"}
${indent(onInitExtra.join("\n"), 3)}
   return INIT_SUCCEEDED;
}

void OnDeinit(const int reason)
{
${indent(indicators.map((h) => h.release).join("\n"), 3)}
${indent(onDeinitExtra.join("\n"), 3)}
}

//─────────────────────────────────────────────────────────────────────
// Tick / bar processing
//─────────────────────────────────────────────────────────────────────
void OnTick()
{
   // 1. Manage open position first (trailing, break-even, etc.)
${indent(positionMgmt.length ? positionMgmt.join("\n") : "// no position management", 3)}

   // 2. New bar gating: most logic only fires once per bar
   if(!ZxIsNewBar()) return;

   // 3. Pre-trade gates
${indent(
  gates.length
    ? gates.map((g) => `if(!${g.expr}) return; // ${escapeComment(g.reason)}`).join("\n")
    : "// no gates",
  3,
)}

   // 4. Entry signals
   bool wantLong  = ${longExpr};
   bool wantShort = ${shortExpr};

   if(wantLong && !PositionSelect(_Symbol))  ZxOpen(ORDER_TYPE_BUY);
   if(wantShort && !PositionSelect(_Symbol)) ZxOpen(ORDER_TYPE_SELL);
}

//─────────────────────────────────────────────────────────────────────
// Order entry
//─────────────────────────────────────────────────────────────────────
void ZxOpen(ENUM_ORDER_TYPE direction)
{
   double entryPrice = (direction == ORDER_TYPE_BUY)
                       ? SymbolInfoDouble(_Symbol, SYMBOL_ASK)
                       : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double slPrice = 0.0;
   double tpPrice = 0.0;

${indent(stopBody, 3)}

   double lots = ${lotExpr};
   if(lots <= 0) { Print("Computed lot size <= 0; skipping entry."); return; }

   if(direction == ORDER_TYPE_BUY)
      Trade.Buy(lots, _Symbol, entryPrice,
                NormalizeDouble(slPrice, _Digits),
                NormalizeDouble(tpPrice, _Digits),
                InpTradeComment);
   else
      Trade.Sell(lots, _Symbol, entryPrice,
                 NormalizeDouble(slPrice, _Digits),
                 NormalizeDouble(tpPrice, _Digits),
                 InpTradeComment);
}

${telemetryHandler}
`;
}

// ───────────────── helpers ─────────────────

function mergeInputs(cs: SectionContribution[]) {
  const seen = new Map<string, ReturnType<() => SectionContribution>["inputs"] extends infer T ? T : never>();
  const out: NonNullable<SectionContribution["inputs"]> = [];
  for (const c of cs) {
    for (const inp of c.inputs ?? []) {
      if (seen.has(inp.name)) continue;
      seen.set(inp.name, undefined as never);
      out.push(inp);
    }
  }
  return out;
}

function mergeIndicators(cs: SectionContribution[]) {
  const seen = new Set<string>();
  const out: NonNullable<SectionContribution["indicators"]> = [];
  for (const c of cs) {
    for (const ind of c.indicators ?? []) {
      if (seen.has(ind.handleVar)) continue;
      seen.add(ind.handleVar);
      out.push(ind);
    }
  }
  return out;
}

function mergeHelpers(cs: SectionContribution[]) {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const c of cs) {
    for (const h of c.helpers ?? []) {
      if (seen.has(h)) continue;
      seen.add(h);
      out.push(h);
    }
  }
  return out;
}

function mergeGlobals(cs: SectionContribution[]) {
  const out: string[] = [];
  for (const c of cs) for (const g of c.globals ?? []) out.push(g);
  return out;
}

function mergeGates(cs: SectionContribution[]) {
  const out: { expr: string; reason: string }[] = [];
  for (const c of cs) for (const g of c.gates ?? []) out.push(g);
  return out;
}

function mergePositionMgmt(cs: SectionContribution[]) {
  const out: string[] = [];
  for (const c of cs) for (const m of c.positionManagement ?? []) out.push(m);
  return out;
}

function mergeStringList(
  cs: SectionContribution[],
  key: "onInitCode" | "onDeinitCode",
): string[] {
  const out: string[] = [];
  for (const c of cs) for (const m of c[key] ?? []) out.push(m);
  return out;
}

function combineEntry(cs: SectionContribution[], dir: SignalDirection): string {
  const exprs: string[] = [];
  for (const c of cs) {
    for (const cond of c.entryConditions ?? []) {
      if (cond.direction === dir || cond.direction === "both") {
        exprs.push(cond.expr);
      }
    }
  }
  if (exprs.length === 0) return "false";
  return exprs.join("\n               && ");
}

function pickSingle<K extends keyof SectionContribution>(
  cs: SectionContribution[],
  key: K,
): SectionContribution[K] | undefined {
  for (const c of cs) if (c[key] !== undefined) return c[key];
  return undefined;
}

function pickSingleStop(cs: SectionContribution[]): string {
  for (const c of cs) if (c.stopLevels) return c.stopLevels.body;
  // Default: no SL/TP
  return "// no stop levels configured\nslPrice = 0.0; tpPrice = 0.0;";
}

function inputsBlock(inputs: NonNullable<SectionContribution["inputs"]>): string {
  if (inputs.length === 0) return "// (no node inputs)";
  return inputs
    .map((i) => `input ${i.type} ${i.name} = ${i.defaultExpr};${i.label ? ` // ${i.label}` : ""}`)
    .join("\n");
}

function indent(text: string, spaces: number): string {
  if (!text) return "";
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((l) => (l.length ? pad + l : l))
    .join("\n");
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, "* /");
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function timeframeEnum(tf: string): string {
  const map: Record<string, string> = {
    M1: "PERIOD_M1", M5: "PERIOD_M5", M15: "PERIOD_M15", M30: "PERIOD_M30",
    H1: "PERIOD_H1", H4: "PERIOD_H4", D1: "PERIOD_D1", W1: "PERIOD_W1", MN1: "PERIOD_MN1",
  };
  return map[tf] ?? "PERIOD_CURRENT";
}

// ──────────────────────────────────────────────────────────────────
// Live telemetry MQL5 snippets
// ──────────────────────────────────────────────────────────────────
// The EA reports every closed deal (identified by DEAL_ENTRY_OUT) to
// the Zentryx Lab telemetry endpoint via WebRequest.
//
// Users must whitelist the telemetry URL once in MT5:
//   Tools → Options → Expert Advisors → "Allow WebRequest for listed URL"
// The EA prints a human-readable hint on OnInit if InpTelemetryOn is true.

function telemetryInputsBlock(): string {
  // Inputs are inlined in the main input block; this is a placeholder to
  // keep the API symmetrical if we later split them out.
  return "";
}

function telemetryHelpersBlock(): string {
  return `// ── Zentryx Lab — live telemetry ─────────────────────────────────
string ZxJsonEscape(string s)
{
   string out = "";
   for(int i = 0; i < StringLen(s); i++) {
      ushort c = StringGetCharacter(s, i);
      if(c == '"')       out += "\\\\\\"";
      else if(c == '\\\\') out += "\\\\\\\\";
      else if(c == '\\n') out += "\\\\n";
      else if(c == '\\r') out += "\\\\r";
      else if(c == '\\t') out += "\\\\t";
      else               out += ShortToString(c);
   }
   return out;
}

string ZxIsoUtc(datetime t)
{
   MqlDateTime d; TimeToStruct(t, d);
   return StringFormat("%04d-%02d-%02dT%02d:%02d:%02dZ", d.year, d.mon, d.day, d.hour, d.min, d.sec);
}

void ZxReportTrade(ulong dealTicket)
{
   if(!InpTelemetryOn) return;
   if(StringLen(InpTelemetryToken) < 8) return;
   if(!HistoryDealSelect(dealTicket)) return;

   // Only report closing deals of our own magic number.
   long magic = HistoryDealGetInteger(dealTicket, DEAL_MAGIC);
   if(magic != InpMagic) return;
   long entry = HistoryDealGetInteger(dealTicket, DEAL_ENTRY);
   if(entry != DEAL_ENTRY_OUT) return;

   ulong   posId      = HistoryDealGetInteger(dealTicket, DEAL_POSITION_ID);
   string  symbol     = HistoryDealGetString(dealTicket, DEAL_SYMBOL);
   double  closePrice = HistoryDealGetDouble(dealTicket, DEAL_PRICE);
   double  lots       = HistoryDealGetDouble(dealTicket, DEAL_VOLUME);
   double  pnl        = HistoryDealGetDouble(dealTicket, DEAL_PROFIT)
                        + HistoryDealGetDouble(dealTicket, DEAL_SWAP)
                        + HistoryDealGetDouble(dealTicket, DEAL_COMMISSION);
   datetime closeTime = (datetime)HistoryDealGetInteger(dealTicket, DEAL_TIME);
   long    dealType   = HistoryDealGetInteger(dealTicket, DEAL_TYPE);
   string  sideStr    = (dealType == DEAL_TYPE_BUY) ? "short" : "long";
   // DEAL_TYPE_BUY on an exit means we closed a short; flip accordingly.
   long    reason     = HistoryDealGetInteger(dealTicket, DEAL_REASON);
   string  reasonStr  = "manual";
   if(reason == DEAL_REASON_SL) reasonStr = "sl";
   else if(reason == DEAL_REASON_TP) reasonStr = "tp";
   else if(reason == DEAL_REASON_SO) reasonStr = "stopout";
   else if(reason == DEAL_REASON_EXPERT) reasonStr = "expert";

   // Find the opening deal for the same position for open_time / open_price.
   datetime openTime = closeTime;
   double   openPrice = closePrice;
   if(HistorySelectByPosition(posId)) {
      int total = HistoryDealsTotal();
      for(int i = 0; i < total; i++) {
         ulong t = HistoryDealGetTicket(i);
         if(t == 0) continue;
         if(HistoryDealGetInteger(t, DEAL_ENTRY) == DEAL_ENTRY_IN) {
            openTime = (datetime)HistoryDealGetInteger(t, DEAL_TIME);
            openPrice = HistoryDealGetDouble(t, DEAL_PRICE);
            break;
         }
      }
   }

   double pipSize = ZxPipSize();
   double pipsSigned = (sideStr == "long")
                      ? (closePrice - openPrice) / pipSize
                      : (openPrice - closePrice) / pipSize;

   double equity  = AccountInfoDouble(ACCOUNT_EQUITY);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   string ccy     = AccountInfoString(ACCOUNT_CURRENCY);
   string broker  = AccountInfoString(ACCOUNT_COMPANY);
   string periodStr = EnumToString((ENUM_TIMEFRAMES)_Period);

   string body = StringFormat(
      "{\\"token\\":\\"%s\\",\\"ticket\\":%I64u,\\"symbol\\":\\"%s\\",\\"timeframe\\":\\"%s\\",\\"side\\":\\"%s\\",\\"open_time\\":\\"%s\\",\\"open_price\\":%.6f,\\"close_time\\":\\"%s\\",\\"close_price\\":%.6f,\\"lots\\":%.4f,\\"pnl_cash\\":%.4f,\\"pnl_pips\\":%.2f,\\"close_reason\\":\\"%s\\",\\"equity_after\\":%.4f,\\"balance_after\\":%.4f,\\"account_currency\\":\\"%s\\",\\"broker\\":\\"%s\\",\\"ea_version\\":\\"1.0.0\\"}",
      ZxJsonEscape(InpTelemetryToken),
      (ulong)posId,
      ZxJsonEscape(symbol),
      ZxJsonEscape(periodStr),
      sideStr,
      ZxIsoUtc(openTime),
      openPrice,
      ZxIsoUtc(closeTime),
      closePrice,
      lots,
      pnl,
      pipsSigned,
      reasonStr,
      equity,
      balance,
      ZxJsonEscape(ccy),
      ZxJsonEscape(broker)
   );

   char postBytes[]; StringToCharArray(body, postBytes, 0, StringLen(body), CP_UTF8);
   char resultBytes[]; string resultHeaders;
   int code = WebRequest("POST", InpTelemetryUrl, "Content-Type: application/json\\r\\n", 5000, postBytes, resultBytes, resultHeaders);
   if(code != 200) {
      Print("Zentryx telemetry POST returned ", code, " (check Tools→Options→Expert Advisors→Allow WebRequest).");
   }
}`;
}

function telemetryHandlerBlock(): string {
  return `//─────────────────────────────────────────────────────────────────────
// OnTradeTransaction — emit telemetry on every closed deal
//─────────────────────────────────────────────────────────────────────
void OnTradeTransaction(const MqlTradeTransaction& trans,
                        const MqlTradeRequest& req,
                        const MqlTradeResult& res)
{
   if(trans.type != TRADE_TRANSACTION_DEAL_ADD) return;
   // Give MT5 a tick to commit the deal to history before reading it.
   ZxReportTrade(trans.deal);
}`;
}
